# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7440e0c63321d64ac363ccc996604d267dfee9c48b1822d125e86e1b7a9ca7f44e1bbc397d0420b0f78eebc305167109588715dd1c936338f61223d5b724c329

test:
  secret_key_base: 7df2aa7b8a994016578c0978c077d525f91faadc8b9dd2f620edc1cf0265f35865de1c4c2be2b00371efc4ae279a1b8fea156c75d0ea2a67d3022186754366d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
